from .main_menu import get_main_reply_keyboard, get_main_menu_keyboard, skip_note_keyboard
from .workout_keyboards import get_workout_type_keyboard, get_intensity_keyboard
from .history_keyboards import history_keyboard